[package]
name = "grep1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
term_size = "0.3.2"
tokio-file-unix = "0.6.0"
